config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :missions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "missions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mission.rb
class Mission < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: %i[ show edit update destroy ]

  # GET /missions or /missions.json
  def index
    @missions = Mission.all
  end

  # GET /missions/1 or /missions/1.json
  def show
  end

  # GET /missions/new
  def new
    @mission = Mission.new
  end

  # GET /missions/1/edit
  def edit
  end

  # POST /missions or /missions.json
  def create
    @mission = Mission.new(mission_params)

    respond_to do |format|
      if @mission.save
        format.html { redirect_to mission_url(@mission), notice: "Mission was successfully created." }
        format.json { render :show, status: :created, location: @mission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/1 or /missions/1.json
  def update
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to mission_url(@mission), notice: "Mission was successfully updated." }
        format.json { render :show, status: :ok, location: @mission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1 or /missions/1.json
  def destroy
    @mission.destroy!

    respond_to do |format|
      format.html { redirect_to missions_url, notice: "Mission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mission_params
      params.require(:mission).permit(:title, :done, :description, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wasteless</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/missions/_form.html.erb
    
<%= form_with(model: mission) do |form| %>
  <% if mission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mission.errors.count, "error") %> prohibited this mission from being saved:</h2>

      <ul>
        <% mission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :done, style: "display: block" %>
    <%= form.check_box :done %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  
<% end %>

app/views/missions/_mission.html.erb
<div class="form">
  <p>
    <strong>Title:</strong>
    <%= mission.title %>
  </p>

  <p>
    <strong>Done:</strong>
    <%= mission.done %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= mission.description %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= mission.date %>
  </p>

</div>

app/views/missions/edit.html.erb
<h1>Editing mission</h1>

<%= render "form", mission: @mission %>

<br>

<div>
  <%= link_to "Show this mission", @mission %> |
  <%= link_to "Back to missions", missions_path %>
</div>

app/views/missions/index.html.erb
 <header>
  <div class="image-container">
    <%= image_tag("Group.svg")%>
</div>
    <h1 class="wasteless">Wasteless</h1>
    <p>Un monde sans <span style="color: #9FC131">déchet</span></p>
    <p>commence par changer nos <span style="color: #9FC131">habitudes</span><P>
  </header>

<h1>Missions</h1>



  <% @missions.each do |mission|%>
    <%= render mission %>
    <p>
      <%= link_to "Show this mission", mission, class: 'mission' %>
    </p>

  <% end %>


  <%= link_to "New mission", new_mission_path, class: 'new_mission' %>

<body>
  <h1 class="titre_1">Progrès</H1>
  <h1 class="semaine_1">Semaine 2</p>

  <div class="rectangle">
    <p class="date_1">JUIL.</p>
    <p class="date_1">02</p>
    <p class="tache">Tâche 4</p>
    <button class="rectangle_effectue">
      <p class="effectue">EFFECTUE</p>
    </button>
  </div>

  <div class="rectangle">
    <p class="date_1">JUIN</p>
    <p class="date_1">29</p>
    <p class="tache">Tâche 3</p>
    <button class="rectangle_effectue">
      <p class="effectue">EFFECTUE</p>
    </button>
  </div>

    <h1 class="semaine_2">Semaine 1</p>
  
  <div class="rectangle">
    <p class="date_1">AOUT</p>
    <p class="date_1">28</p>
    <p class="tache">Tâche 2</p>
    <button class="rectangle_effectue">
      <p class="effectue">EFFECTUE</p>
    </button>
  </div>

  <div class="rectangle">
    <p class="date_1">JUIN 21</p>
    <p class="tache">Tâche 1</p>
    <button class="rectangle_effectue">
      <p class="effectue">EFFECTUE</p>
    </button>
  </div>

  </body>

 

</html>

app/views/missions/new.html.erb
<h1>New mission</h1>

<%= render "form", mission: @mission %>

<br>

<div>
  <%= link_to "Back to missions", missions_path %>
</div>

app/views/missions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mission %>

<div>
  <%= link_to "Edit this mission", edit_mission_path(@mission) %> |
  <%= link_to "Back to missions", missions_path %>

  <%= button_to "Destroy this mission", @mission, method: :delete %>
</div>